name: sal7ly_firebase
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_slidable:
  shimmer: ^1.1.0
  splashscreen: ^1.2.0
  image_picker:
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+5
  firebase_database: ^3.1.1
  firebase_storage: ^3.0.3
  google_sign_in:
  http: ^0.12.0+2
  flutter_auth_buttons: ^0.3.1
  geolocator: ^5.2.1
  fluttertoast: ^3.1.3
  provider: ^4.0.4
  google_maps_flutter: ^0.5.21+8
  permission_handler:
  flutter_local_notifications:
  firebase_messaging:
  page_view_indicator: ^2.0.4
  shared_preferences: ^0.5.6+3
  font_awesome_flutter: ^8.0.1
  cupertino_icons: ^0.1.2
  pattern_formatter: ^1.0.1
  flutter_svg: ^0.17.4
  international_phone_input: ^1.0.4
  intl_phone_number_input: ^0.4.2
  flutter_rating_bar: ^3.0.1+1
  geocoder: ^0.2.1
  android_intent: ^0.3.7+2
  animated_text_kit: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/Splash.png
    - assets/SALHLY.png
    - assets/first.png
    - assets/location.png
    - assets/location.svg
    - assets/icons/near.svg
    - assets/Logo.png
    - assets/Logo.jpg
    - assets/onBoarding/

  fonts:
  - family: Bold
    fonts:
      - asset: fonts/OpenSans-Bold.ttf

  - family: Light
    fonts:
      - asset: fonts/OpenSans-Light.ttf

  - family: Boldd
    fonts:
      - asset: fonts/QanelasSoft-Bold.otf

  - family: Regular
    fonts:
      - asset: fonts/OpenSans-Regular.ttf

  - family: SemiBold
    fonts:
      - asset: fonts/OpenSans-SemiBold.ttf

  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
 #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
